# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_iserdes/cmd_iserdes.xci
# IP: The module: 'cmd_iserdes' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_iserdes/cmd_iserdes_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_iserdes'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_iserdes/cmd_iserdes.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_iserdes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_iserdes/cmd_iserdes.xci
# IP: The module: 'cmd_iserdes' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_iserdes/cmd_iserdes_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_iserdes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_iserdes/cmd_iserdes.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmd_iserdes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
