# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora_fmc_one_lane/aurora_fmc_one_lane.cache/wt [current_project]
set_property parent.project_path /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora_fmc_one_lane/aurora_fmc_one_lane.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.3 [current_project]
set_property ip_output_repo /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora_fmc_one_lane/aurora_fmc_one_lane.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/pixdaq/kdunne/aurora_fmc_one_lane/src/aurora_fmc_one_lane_top.sv
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/ber.sv
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/bitslip_fsm.sv
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/gearbox_66_to_32.sv
  /home/pixdaq/kdunne/aurora_fmc_one_lane/src/aurora_8_pair_top.sv
}
read_verilog -library xil_defaultlib {
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/ber_scrambler.v
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/block_sync.v
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/Verilog_macros/delay_controller_wrap.v
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/descrambler.v
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/gearbox_32_to_66.v
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/scrambler.v
  /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/Verilog_macros/serdes_1_to_468_idelay_ddr.v
}
read_vhdl -library xil_defaultlib /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/imports/aurora/lcd_driver.vhd
read_ip -quiet /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_oserdes/cmd_oserdes.xci
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_oserdes/cmd_oserdes_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/cmd_oserdes/cmd_oserdes.xdc]

read_ip -quiet /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]

read_ip -quiet /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc]
set_property used_in_implementation false [get_files -all /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/constrs_1/imports/constraints/aurora_fmc_one_lane.xdc
set_property used_in_implementation false [get_files /home/pixdaq/kdunne/aurora_fmc_one_lane/aurora.srcs/constrs_1/imports/constraints/aurora_fmc_one_lane.xdc]


synth_design -top aurora_8_pair_top -part xc7vx485tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef aurora_8_pair_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file aurora_8_pair_top_utilization_synth.rpt -pb aurora_8_pair_top_utilization_synth.pb"
